django/project-home/employee/urls.py
from django.urls import path
from .import views
from django.conf.urls import url
from django.contrib import admin

app_name='employee'

urlpatterns=[
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view(),name='index'),
    path('detail/<int:pk>/',  views.DetailView.as_view(), name='detail'),]

django/project-home/project2/urls.py
from django.contrib import admin
from django.urls import path, include


#django管理画面のカスタマイズ
admin.site.site_header = '学級日誌'
admin.site.index_title = 'メニュー'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]

django/project-home/employee/models.py
from django.db import models
from django.utils import timezone

class Class(models.Model):
    name = models.CharField('クラス名', max_length=20)
    def __str__(self):
        return self.name

class Record(models.Model):
    #ほかのモデルと紐づける
    department = models.ForeignKey(
        Class, verbose_name='クラス:', on_delete=models.PROTECT,
    )
    created_at = models.DateField('日付:', default=timezone.now)
    person = models.CharField('記録者:', max_length=20, blank=False, null=False)
    event = models.CharField('学校行事・連絡事項:', max_length=50, blank=True, null=True)
    weather = models.CharField('天気:', max_length=10, blank=False, null=False)
    subject1 = models.CharField('1校時:科目:',max_length=10, blank=True, null=True)
    substance1 = models.CharField('↑内容↑:',max_length=30, blank=True, null=True)
    subject2 = models.CharField('2校時:科目:',max_length=10, blank=True, null=True)
    substance2 = models.CharField('↑内容↑:',max_length=30, blank=True, null=True)
    subject3 = models.CharField('3校時:科目:',max_length=10, blank=True, null=True)
    substance3 = models.CharField('↑内容↑:',max_length=30, blank=True, null=True)
    subject4 = models.CharField('4校時:科目:',max_length=10, blank=True, null=True)
    substance4 = models.CharField('↑内容↑:',max_length=30, blank=True, null=True)
    cleaning1 = models.CharField('教室掃除:',max_length=30, blank=True, null=True)
    cleaning2 = models.CharField('特別区域掃除:',max_length=30, blank=True, null=True)
    feel = models.TextField('所感:', blank=False, null=False)
    teacher = models.TextField('先生から:', blank=True, null=True)
    def __str__(self):
        return '{0} {1}'.format(self.department, self.person)

django/project-home/employee/views.py
from django.views import generic
from django.shortcuts import render
from .models import Record

class IndexView(generic.ListView):
    model = Record
    def get_queryset(self):
        #並び替え：作成日が新しい順に並べる
        return Record.objects.order_by('-created_at')

class DetailView(generic.DetailView):
    model=Record
    
def index(request):
    return render(request, 'employee/base.html')

django/project-home/employee/templates/employee/base.html
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">

        <title>学級日誌</title>
    </head>
    <body class="scroll_lock">
        {% block loading %}
        <div id="loading">
            <img src="../../static/image/logo.jpg" alt="" id="logo">
            <p id="load-text">loading...</p>
        </div>
        {% endblock %}
        <nav class="navbar navbar-expand-lg navbar-dark " style="background-color: #4072B3;">
            <div class="container-fluid">
            <a class="navbar-brand" href="#">学級日誌</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">/</a>
                </li>
                <li class="nav-item">
                    <!-- admin管理サイトへのリンク -->
                    <a class="nav-link" href="{% url 'admin:index' %}">管理サイト</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://www.ichinoseki.ac.jp/" tabindex="-1" aria-disabled="true">一関高専HP</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://edu.ichinoseki.ac.jp/moodle/" tabindex="-1" aria-disabled="true">一関高専Moodle</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        その他
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% static 'use/use.html' %}">使い方</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="https://freecalend.com/open/mem174061">カレンダー</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% static 'drowing/index.html' %}">お絵描き</a></li>
                    </ul>
                </li>
                </ul>
            </div>
            </div>
        </nav>
        <!-- jumbotron -->
        <div class="jumbotron" style="margin-left: 3rem;">
            <h1 class="display-4" style=" margin: 2rem; font-weight: bold;">ようこそweb版学級日誌へ!!</h1>
            <p class="lead" style="margin-left: 3rem;">日々のちょっとしためんどくさいを解決。</p>
            <hr class="my-4">
            <p style="margin-left: 3rem;">より良いクラスへの一歩になりますように</p>
            <p class="lead" style="margin: 1rem 0 1rem 3rem;">
            <a class="btn btn-primary btn-lg" href="{% url 'admin:index' %}" role="button" style="background-color: #4072B3;">今日の日誌を書く</a>
            </p>
        </div>
        <div class="container" style="background-color: #c0c0c030;">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                    <!--<a class="more" src="#" style="text-decoration: none; font-size: 1.5rem; color: #4072B3; margin: 0.5rem;">💬過去の日誌をもっと見る</a>-->
                </div>
                <div class="col-md-4" style="margin-top: 2rem; height: auto;">
                    <ul class="list-group">
                        <div class="list1">
                            <li class="list-group-item" style="background-color: #4072B3; color: white;">カレンダー📅</li>
                            <iframe src="https://freecalend.com/open/mem174061" id="calender" onload="siteLoaded()" style="height: 50vh; width: 57vh;"></iframe>
                            <li class="calendar" style="margin-bottom: 1rem; font-size: 1.3rem;"><a href="https://m174061.freecalend.com/calmem_index" class="calemdar" style="color: #4072B3; text-decoration: none;">カレンダーに予定を書きこむ >>></a></li>
                        </div>
                        <div class="list2">
                            <li class="list-group-item" style="background-color: #4072B3; color: white;">お絵描き🎨</li>
                            <iframe src="{% static 'drowing/index.html' %}" id="drow" onload="siteLoaded()" style="height: 50vh; width: 57vh;"></a></iframe>
                            <li class="drow" style="margin-bottom: 1rem; font-size: 1.3rem;"><a href="{% static 'drowing/index.html' %}" class="drow" style="color: #4072B3; text-decoration: none;">お絵描きする >>></a></li>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
        <!-- footer -->
        <footer class="text-white text-center py-3" style="background-color: #4072B3; margin-top: 3rem;">
            <a class="back-home" style="text-decoration: none; color: white;">HPに戻る</a>
        </footer>
        <!-- jsの外部ファイル -->
        <!-- dropdownとtoggle -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        <!-- ローディング画面 -->
        <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    </body>
</html>

django/project-home/employee/templates/employee/record_detail.html
{% extends 'employee/base.html' %}
{% block loading %}

{% endblock %}
{% block content %}
<div class="card-body">
    <h3 class="card-header" style="background-color: #4072B3; color: white;">{{ record.created_at }}</h3>
    <h6class="card-subtitle mb-2 text-muted">記録者：{{ record.person }}</h6class=>
    <p class="card-text" style="margin: 1rem;">学校行事・連絡事項：{{ record.event }}</p>
    <p class="card-text" style="margin: 1rem;">天気：{{ record.weather }}</p>
    <p class="card-text" style="margin: 1rem;">1校時：科目：{{ record.subject1 }}</p>
    <p class="card-text" style="margin: 1rem;">↑内容↑：{{ record.substance1 }}</p>
    <p class="card-text" style="margin: 1rem;">2校時：科目：{{ record.subject2 }}</p>
    <p class="card-text" style="margin: 1rem;">↑内容↑：{{ record.substance2 }}</p>
    <p class="card-text" style="margin: 1rem;">3校時：科目：{{ record.subject3 }}</p>
    <p class="card-text" style="margin: 1rem;">↑内容↑：{{ record.substance3 }}</p>
    <p class="card-text" style="margin: 1rem;">4校時：科目：{{ record.subject4 }}</p>
    <p class="card-text" style="margin: 1rem;">↑内容↑：{{ record.substance4 }}</p>
    <p class="card-text" style="margin: 1rem;">教室掃除：{{ record.cleaning1 }}</p>
    <p class="card-text" style="margin: 1rem;">特別教室掃除：{{ record.cleaning2 }}</p>
    <p class="card-text" style="margin: 1rem;">所感：{{ record.feel }}</p>
    <p class="card-text" style="margin: 1rem;">先生から：{{ record.teacher }}</p>

    <a href="{% url 'employee:index' %}" class="card-link" style="text-decoration: none;"> ≺≺≺ back</a>
    <!-- 改行フィルター -->
    {{ record.text | linebreaksbr }}
</div>
{% endblock %}

django/project-home/employee/templates/employee/record_list.html
{% extends 'employee/base.html' %}
<!--base.htmlのcontentを上書き-->
    {% block content %}
    <!--記事を一つずつ獲得できる-->
    {% for record in record_list %}
    <div class="card my-3" style="width: 80%;">
        <div class="card-body">
            <h3 class="card-header" style="background-color: #4072B3; color: white;">{{ record.created_at }}</h3>
            <h6 class="card-subtitle mb-2 text-muted" style="margin-top: 0.3rem;">記録者：{{ record.person }}</h6>
            <p class="card-text" style="margin: 1rem;">所感：{{ record.feel }}</p>
            <p class="card-text" style="margin: 1rem; font-weight: bold;">先生から：{{ record.teacher }}</p>
            <a href="{% url 'employee:detail' record.pk %}" class="card-link" style="text-decoration: none;">Show More ≻≻≻</a>
        </div>
    </div>
    <!--  {% if forloop.counter <= 5 %}  -->
    <!--  {% endif %}  -->
    {% endfor %}
    
    {% endblock %}